name: GitHub Pages Deployment

# Trigger deployment on every push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Deploy directly to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./                 # HTML/CSS/images are in repo root
          artifact_name: gh-pages-artifact-${{ github.run_id }}  # unique artifact name
          clean: true                     # clean old files to prevent stale content

      # 3️⃣ Confirmation message
      - name: Deployment Success
        run: echo "✅ GitHub Pages deployed successfully!"
