name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # triggers deployment on push to main

permissions:
  contents: read   # required to read repository contents
  pages: write     # required to deploy to GitHub Pages
  id-token: write  # required for authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3. Upload files for deployment
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./   # deploy from root (where index.html is)

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
